Kr1ptal/ethers-kt

ethers-providers/src/main/kotlin/io/ethers/providers/types/BatchRpcRequest.kt

feat(providers): function to unwrap all batch responses

---

ethers-core/src/main/kotlin/io/ethers/core/types/Block.kt
ethers-core/src/test/kotlin/io/ethers/core/types/BlockTest.kt

Based on https://eips.ethereum.org/EIPS/eip-4788

feat(core): add support for eip-4788 `parentBeaconBlockRoot` header field

---

buildSrc/src/main/kotlin/java-toolchain-conventions.gradle.kts
ethers-abi/src/main/kotlin/io/ethers/abi/EventFilters.kt
ethers-abi/src/main/kotlin/io/ethers/abi/call/ContractCall.kt
ethers-core/src/main/kotlin/io/ethers/core/Result.kt
ethers-ens/src/main/kotlin/io/ethers/ens/EnsMiddleware.kt
ethers-providers/src/main/kotlin/io/ethers/providers/types/Result.kt
ethers-providers/src/main/kotlin/io/ethers/providers/types/RpcRequest.kt
ethers-providers/src/main/kotlin/io/ethers/providers/types/RpcSubscribe.kt

A generic `Result` implementation to replace the `RpcResponse` type. Contains many improvements:
- additional functional methods
- fully typed errors
- better ergonomics and potential performance (via JIT inlining)

feat: new Result type

---

ethers-abi/src/main/kotlin/io/ethers/abi/AbiCodec.kt
ethers-abi/src/main/kotlin/io/ethers/abi/AbiEvent.kt
ethers-abi/src/main/kotlin/io/ethers/abi/AbiFunction.kt
ethers-abi/src/main/kotlin/io/ethers/abi/error/ContractError.kt
ethers-abi/src/test/kotlin/io/ethers/abi/AbiFunctionTest.kt
ethers-core/src/main/kotlin/io/ethers/core/types/Address.kt
ethers-core/src/main/kotlin/io/ethers/core/types/Bloom.kt
ethers-core/src/main/kotlin/io/ethers/core/types/Bytes.kt
ethers-core/src/main/kotlin/io/ethers/core/types/Hash.kt
ethers-core/src/main/kotlin/io/ethers/core/types/transaction/TxBlob.kt
ethers-core/src/test/kotlin/io/ethers/core/types/transactions/TransactionSignedTest.kt
ethers-ens/src/main/kotlin/io/ethers/ens/EnsMiddleware.kt
ethers-signers/src/main/kotlin/io/ethers/signers/PrivateKeySigner.kt
examples/src/main/kotlin/io/ethers/examples/functionselectors/FunctionSelectors.kt

feat!(core): encapsulate `value` in `Address`/`Hash`/`Bytes` and expose it via `toByteArray` function

---

ethers-core/src/main/kotlin/io/ethers/core/FastHex.kt
ethers-core/src/main/kotlin/io/ethers/core/types/CallRequest.kt
ethers-core/src/test/kotlin/io/ethers/core/JacksonTest.kt
ethers-providers/src/main/kotlin/io/ethers/providers/Provider.kt
ethers-providers/src/main/kotlin/io/ethers/providers/middleware/DebugApi.kt
ethers-providers/src/main/kotlin/io/ethers/providers/middleware/EthApi.kt
ethers-providers/src/main/kotlin/io/ethers/providers/types/CallManyTypes.kt
ethers-providers/src/test/kotlin/io/ethers/providers/types/CallManyTypesTest.kt

feat(providers): add `eth_callMany`/`debug_traceCallMany` RPC calls

---

ethers-abi/src/main/kotlin/io/ethers/abi/call/ContractCall.kt
ethers-core/src/main/kotlin/io/ethers/core/JsonParserExtensions.kt
ethers-core/src/main/kotlin/io/ethers/core/types/AccountOverride.kt
ethers-core/src/main/kotlin/io/ethers/core/types/BlockOverride.kt
ethers-core/src/main/kotlin/io/ethers/core/types/tracers/PrestateTracer.kt
ethers-core/src/test/kotlin/io/ethers/core/types/AccountOverrideTest.kt
ethers-core/src/test/kotlin/io/ethers/core/types/tracers/PrestateTracerTest.kt
ethers-providers/src/main/kotlin/io/ethers/providers/HttpClient.kt
ethers-providers/src/main/kotlin/io/ethers/providers/Provider.kt
ethers-providers/src/main/kotlin/io/ethers/providers/middleware/EthApi.kt

feat(core): add function to `PrestateTracer.Result` to create state override from state diff

---

ethers-core/src/main/kotlin/io/ethers/core/types/tracers/CallTracer.kt

feat(core): add support for converting `CallTracer#CallLog` into `Log`, and returning all logs from a `CallFrame`

---

ethers-providers/src/main/kotlin/io/ethers/providers/types/BatchRpcRequest.kt

fix(providers): add missing list append in `List<CompletableFuture<T>>.await()` extension function

---

ethers-providers/src/main/kotlin/io/ethers/providers/HttpClient.kt
ethers-providers/src/main/kotlin/io/ethers/providers/JsonRpcClient.kt
ethers-providers/src/main/kotlin/io/ethers/providers/Provider.kt
ethers-providers/src/main/kotlin/io/ethers/providers/WsClient.kt
examples/src/main/kotlin/io/ethers/examples/tokenswapwitheventlistening/TokenSwapWithEventListening.kt

feat!(providers): add RpcClientConfig for configuring JsonRpcClient implementations

---

ethers-abi/src/main/kotlin/io/ethers/abi/AbiCodec.kt
ethers-abi/src/test/kotlin/io/ethers/abi/AbiCodecTest.kt

fix(abi): fix decoding arrays of type Bytes/FixedBytes

---

ethers-abi/src/main/kotlin/io/ethers/abi/AbiCodec.kt
ethers-abi/src/main/kotlin/io/ethers/abi/AbiConstructor.kt
ethers-abi/src/main/kotlin/io/ethers/abi/AbiEvent.kt
ethers-abi/src/main/kotlin/io/ethers/abi/AbiFunction.kt
ethers-abi/src/main/kotlin/io/ethers/abi/AbiType.kt
ethers-abi/src/main/kotlin/io/ethers/abi/ContractStruct.kt
ethers-abi/src/main/kotlin/io/ethers/abi/call/Multicall3.kt
ethers-abi/src/main/kotlin/io/ethers/abi/error/ContractError.kt
ethers-abi/src/test/kotlin/io/ethers/abi/AbiCodecTest.kt
ethers-abi/src/test/kotlin/io/ethers/abi/AbiEventTest.kt
ethers-abi/src/test/kotlin/io/ethers/abi/AbiFunctionTest.kt
ethers-abi/src/test/kotlin/io/ethers/abi/error/CustomErrorTest.kt
ethers-abigen-plugin/src/main/kotlin/io/ethers/abigen/plugin/task/EthersAbigenTask.kt
ethers-abigen/src/main/kotlin/io/ethers/abigen/AbiContractBuilder.kt
ethers-abigen/src/main/kotlin/io/ethers/abigen/AbiTypeParameter.kt
ethers-ens/src/main/kotlin/io/ethers/ens/EnsMiddleware.kt

The build will fail until a new version of the abigen plugin is released, because this PR introduces breaking changes.

feat!(abi): generify `AbiType`

---

ethers-core/src/main/kotlin/io/ethers/core/FastHex.kt

File header block comment added to FastHex.kt
In order to satisfy the original source's license requirement (Apache 2.0).
File header added with attribution and notice of modifications.

add attribution to FastHex.kt

---

examples/src/main/kotlin/io/ethers/examples/batchrequests/Multicall.kt

We want to showcase the newly implemented support for aggregating contract calls into Multicall3 that was introduced with v0.4.0 release.
We implemented Multicall example which demonstrates how to aggregate contract calls into Multicall3.

feat(examples): add Multicall example

---

ethers-providers/src/main/kotlin/io/ethers/providers/middleware/EthApi.kt

feat(eth-api): Add documentation for rewardPercentiles value range.

---

ethers-abigen-plugin/src/main/kotlin/io/ethers/abigen/plugin/task/EthersAbigenTask.kt
ethers-abigen/src/main/kotlin/io/ethers/abigen/AbiContractBuilder.kt

feat(abigen): suppress IDE inspections in generated contract wrappers

---

.github/actions/environment-setup/action.yml
.github/workflows/pull-request-checks.yml

misc(ci): update gradle GH action to gradle/actions/setup-gradle@v3

---

ethers-providers/src/main/kotlin/io/ethers/providers/HttpClient.kt
ethers-providers/src/main/kotlin/io/ethers/providers/JsonRpcClient.kt
ethers-providers/src/main/kotlin/io/ethers/providers/Provider.kt
ethers-providers/src/main/kotlin/io/ethers/providers/SubscriptionStream.kt
ethers-providers/src/main/kotlin/io/ethers/providers/WsClient.kt
ethers-providers/src/main/kotlin/io/ethers/providers/middleware/Middleware.kt
ethers-providers/src/main/kotlin/io/ethers/providers/types/RpcSubscribe.kt

refactor(providers): merge `JsonPubSubClient` into `JsonRpcClient`

---

ethers-core/src/main/kotlin/io/ethers/core/types/transaction/TransactionSigned.kt
ethers-core/src/main/kotlin/io/ethers/core/types/transaction/TransactionUnsigned.kt
ethers-core/src/main/kotlin/io/ethers/core/types/transaction/TxAccessList.kt
ethers-core/src/main/kotlin/io/ethers/core/types/transaction/TxBlob.kt
ethers-core/src/main/kotlin/io/ethers/core/types/transaction/TxDynamicFee.kt
ethers-core/src/main/kotlin/io/ethers/core/types/transaction/TxLegacy.kt
ethers-core/src/test/kotlin/io/ethers/core/types/transactions/TransactionSignedTest.kt
ethers-providers/src/main/kotlin/io/ethers/providers/Provider.kt
ethers-signers/src/test/kotlin/io/ethers/signers/PrivateKeySignerTest.kt

refactor!: make `access list` property immutable on unsigned txs, replace `rlpEncodeFields` with `rlpEncodeEnveloped`

---

ethers-abi/src/main/kotlin/io/ethers/abi/call/ContractCall.kt
ethers-core/src/main/kotlin/io/ethers/core/types/CallRequest.kt
ethers-providers/src/main/kotlin/io/ethers/providers/Provider.kt
ethers-providers/src/main/kotlin/io/ethers/providers/types/RpcRequest.kt

According to ethereum JSON-RPC specs, the `eth_fillTransaction` is not standardized. It's currently missing at least on Reth nodes. This PR makes the provider fall-back to manually fetching the necessary data to fill the TX.
Specs: https://ethereum.github.io/execution-apis/api-documentation/

feat(providers): manually fill missing transaction details if `eth_fillTransaction` is not supported

---

ethers-abigen/src/main/kotlin/io/ethers/abigen/AbiContractBuilder.kt
ethers-abigen/src/test/kotlin/io/ethers/abigen/cases/FunctionsTest.kt
ethers-abigen/src/test/resources/abi/Functions.json
ethers-abigen/src/test/solidity/src/Functions.sol

fix(abigen): fix abigen of overloaded functions with same java types

---

ethers-abigen-plugin/src/main/kotlin/io/ethers/abigen/plugin/task/EthersAbigenTask.kt
ethers-abigen/src/main/kotlin/io/ethers/abigen/AbiContractBuilder.kt
ethers-abigen/src/main/kotlin/io/ethers/abigen/AbiTypeParameter.kt
ethers-abigen/src/test/kotlin/io/ethers/abigen/cases/FunctionsTest.kt
ethers-abigen/src/test/resources/abi/Functions.json
ethers-abigen/src/test/solidity/src/Functions.sol

feat(abigen): add docs to generated contract bindings

---

ethers-abigen-plugin/README.md
ethers-abigen-plugin/build.gradle.kts
ethers-abigen-plugin/src/main/kotlin/io/ethers/abigen/plugin/EthersAbigenExtension.kt
ethers-abigen-plugin/src/main/kotlin/io/ethers/abigen/plugin/source/FoundrySourceProvider.kt
ethers-abigen-plugin/src/main/kotlin/io/ethers/abigen/plugin/task/EthersAbigenTask.kt
gradle/libs.versions.toml

feat(abigen-plugin): add support for auto-generating bindings for foundry projects

---

ethers-abigen-plugin/src/main/kotlin/io/ethers/abigen/plugin/source/FoundrySourceProvider.kt

Fixes #166
All properties need to be lazy-evaluated so the foundry dir can be defined in non-standard locations.

fix(abigen-plugin): lazy-evaluate all input properties of `FoundrySourceProvider`

---

ethers-abi/build.gradle.kts
ethers-abigen-plugin/build.gradle.kts
ethers-abigen/build.gradle.kts
ethers-crypto/src/main/kotlin/io/ethers/crypto/ECDSASignerRecoverable.kt
ethers-ens/build.gradle.kts
ethers-providers/build.gradle.kts
ethers-signers-gcp/build.gradle.kts
ethers-signers/build.gradle.kts

feat: change dependency visibility to `api` for submodules

---

ethers-crypto/src/main/kotlin/io/ethers/crypto/Hashing.kt
ethers-crypto/src/main/kotlin/io/ethers/crypto/bip39/MnemonicCode.kt
ethers-signers/src/main/kotlin/io/ethers/signers/PrivateKeySigner.kt

feat(signers): add support for creating random `PrivateKeySigner`

---

ethers-providers/src/main/kotlin/io/ethers/providers/HttpClient.kt
ethers-providers/src/main/kotlin/io/ethers/providers/JsonRpcClient.kt
ethers-providers/src/main/kotlin/io/ethers/providers/WsClient.kt
ethers-providers/src/main/kotlin/io/ethers/providers/types/BatchRpcRequest.kt

feat(providers): properly unsubscribe `WsClient` streams and expire all remaining requests on client close

---

ethers-providers/src/main/kotlin/io/ethers/providers/AsyncExecutor.kt
ethers-providers/src/main/kotlin/io/ethers/providers/JsonRpcClient.kt
ethers-providers/src/main/kotlin/io/ethers/providers/SubscriptionStream.kt
ethers-providers/src/main/kotlin/io/ethers/providers/WsClient.kt
ethers-providers/src/main/kotlin/io/ethers/providers/types/RpcRequest.kt

feat!: try to use virtual threads if present and enabled

---

ethers-abigen-plugin/src/main/kotlin/io/ethers/abigen/plugin/source/DirectorySourceProvider.kt

fix(abigen-plugin): normalize Windows file paths

---

ethers-providers/src/main/kotlin/io/ethers/providers/WsClient.kt

- treat unrecognized WS JSON as invalid and return `RpcError.CODE_INVALID_RESPONSE`
- on invalid responses with an ID, fail the waiting request with that error
- `./gradlew --no-daemon ktlintFormat check`

Handle invalid WS responses

---

ethers-providers/src/main/kotlin/io/ethers/providers/JsonRpcClient.kt
ethers-providers/src/main/kotlin/io/ethers/providers/Provider.kt

fix(providers): handle more `RpcError#isMethodNotFound` cases

---

ethers-abigen-plugin/src/main/kotlin/io/ethers/abigen/plugin/source/DirectorySourceProvider.kt
ethers-abigen/src/main/kotlin/io/ethers/abigen/ErrorLoaderBuilder.kt

fix(abigen)!: lowercase ABI class names and flat package structure generation

---

ethers-core/src/main/kotlin/io/ethers/core/types/Txpool.kt
ethers-ens/src/test/kotlin/io/ethers/ens/EnsMiddlewareTest.kt
ethers-providers/src/main/kotlin/io/ethers/providers/HttpClient.kt
ethers-providers/src/main/kotlin/io/ethers/providers/Provider.kt
ethers-providers/src/main/kotlin/io/ethers/providers/WsClient.kt
ethers-providers/src/main/kotlin/io/ethers/providers/types/BatchRpcRequest.kt
ethers-providers/src/test/kotlin/io/ethers/providers/HttpClientTest.kt
ethers-providers/src/test/kotlin/io/ethers/providers/JsonRpcClientTestFactory.kt
ethers-providers/src/test/kotlin/io/ethers/providers/JsonRpcTestFactory.kt
ethers-providers/src/test/kotlin/io/ethers/providers/MockServer.kt
ethers-providers/src/test/kotlin/io/ethers/providers/WsClientTest.kt
logger/src/main/kotlin/io/ethers/logger/LoggerExtensions.kt

feat: support out-of-order batch responses

---

ethers-signers-gcp/src/main/kotlin/io/ethers/signers/GcpSigner.kt

refactor!: `GcpSigner` constructor no longer does an external call

---

ethers-core/src/main/kotlin/io/ethers/core/HexDecodingError.kt
ethers-core/src/main/kotlin/io/ethers/core/types/Address.kt
ethers-core/src/main/kotlin/io/ethers/core/types/Bloom.kt
ethers-core/src/main/kotlin/io/ethers/core/types/Bytes.kt
ethers-core/src/main/kotlin/io/ethers/core/types/Hash.kt

feat: add fromHex/fromHexUnsafe helper functions to low-level types

---

buildSrc/src/main/kotlin/ktlint-conventions.gradle.kts
ethers-abigen-plugin/src/main/kotlin/io/ethers/abigen/plugin/EthersAbigenExtension.kt
ethers-abigen-plugin/src/main/kotlin/io/ethers/abigen/plugin/EthersAbigenPlugin.kt
ethers-abigen-plugin/src/main/kotlin/io/ethers/abigen/plugin/source/DirectorySourceProvider.kt
ethers-abigen-plugin/src/main/kotlin/io/ethers/abigen/plugin/source/FoundrySourceProvider.kt
ethers-abigen-plugin/src/main/kotlin/io/ethers/abigen/plugin/task/EthersAbigenTask.kt
gradle.properties
settings.gradle.kts

feat: gradle config cache

---

ethers-abi/src/main/kotlin/io/ethers/abi/AbiStruct.kt
ethers-abi/src/test/kotlin/io/ethers/abi/eip712/EIP712TypedDataTest.kt
examples/src/main/abi/io/ethers/examples/gen/Seaport_1_6.json
examples/src/main/kotlin/io/ethers/examples/eip712/EIP712SeaportOrderSigning.kt

feat: add seaport EIP712 signing example
